[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openni-python3"
version = "2.4.0"
description = "OpenNI2 and NiTE2 Python 3.8+ bindings"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    {name = "PrimeSense Inc, Séverin Lemaignan, Jerome Flesch, Hajime Murao, Graoui Abderrahmane"}
]
keywords = ["PrimeSense", "OpenNI", "OpenNI2", "Natural Interaction", "NiTE", "NiTE2"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/MerGr/openni-python3"
